# Generated by Django 3.1.5 on 2021-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
